### ISSUE TITLE
Unable to parse otdr1.sor - pyOTDR parses it ok

### ISSUE THREAD

**Issue by jaredmauch** [mjuenema/otdrparser#4]
latin-1 vs utf-8 handling of file that is binary opened looks to be causing a problem.  here's a few files (attached) that trigger this issue

[example_files.zip](https://github.com/user-attachments/files/18083013/example_files.zip)

**Comment by jaredmauch** [comment]
created PR, please review

**Comment by mjuenema** [comment]
I merged the pull requests. All OTDR traces you supplied can be parsed. Thanks for your contribution.
